name: markovbot
description: A bot that uses a Markov chain to flood on your Discord server :) 
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  nyxx: ^3.2.6
